### ISSUE TITLE
Integration tests failing locally, passing in CI

### ISSUE THREAD

**Issue by emilywatkins** [concord-consortium/rigse#551]
The following tests fail locally when running entire cucumber suite, running the individual file, and the individual test. However, they're passing in CI.

```
(::) failed steps (::)

undefined method `click' for nil:NilClass (NoMethodError)
./features/step_definitions/web_steps.rb:89:in `/^(?:|I )follow "([^"]*)"$/'
features/teacher_navigates_classes_using_left_pane.feature:19:in `And I follow "Student Roster"'

undefined method `click' for nil:NilClass (NoMethodError)
./features/step_definitions/web_steps.rb:89:in `/^(?:|I )follow "([^"]*)"$/'
features/teacher_navigates_classes_using_left_pane.feature:25:in `And I follow "Class Setup"'

undefined method `click' for nil:NilClass (NoMethodError)
./features/step_definitions/web_steps.rb:89:in `/^(?:|I )follow "([^"]*)"$/'
features/teacher_navigates_classes_using_left_pane.feature:31:in `And I follow "Assignments"'

Failing Scenarios:
cucumber features/teacher_navigates_classes_using_left_pane.feature:17 # Scenario: Teacher visits Student Roster page
cucumber features/teacher_navigates_classes_using_left_pane.feature:23 # Scenario: Teacher visits Class Setup page
cucumber features/teacher_navigates_classes_using_left_pane.feature:29 # Scenario: Teacher visits Materials page
```

**Comment by scytacki** [comment]
The navigation those tests are using is about to be replaced: https://github.com/concord-consortium/rigse/pull/524 So you might want to check out that branch and see if they are still failing.
